/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.20
 * Generated at: 2026-04-11 11:44:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.includes;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String currentPage_sidebar = request.getRequestURI();
    String pageName = currentPage_sidebar.substring(currentPage_sidebar.lastIndexOf("/") + 1);
    String ctx = request.getContextPath();

      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <h2><a href=\"");
      out.print( ctx );
      out.write("/admin\" class=\"admin-title\">\r\n");
      out.write("            <i class=\"fa-solid fa-screwdriver-wrench\"></i> Admin Panel\r\n");
      out.write("        </a></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/product\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/product") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-box\"></i> Quản lý sản phẩm\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/order\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/order") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-receipt\"></i> Quản lý đơn hàng\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/category\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/category") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-layer-group\"></i> Quản lý danh mục\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/customer\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/customer") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-users\"></i> Quản lý khách hàng\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/review\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/review") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-comments\"></i> Quản lý bình luận\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/coupon\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/coupon") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-ticket\"></i> Mã giảm giá\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/statistic\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/statistic") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-chart-line\"></i> Thống kê\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( ctx );
      out.write("/admin/announcements\" class=\"");
      out.print( currentPage_sidebar.contains("/admin/announcements") ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-bell\"></i> Thông báo\r\n");
      out.write("            </a></li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/client/logout\" class=\"logout-link\">\r\n");
      out.write("                <i class=\"fa-solid fa-right-from-bracket\"></i> Đăng xuất\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
